echo -e "\e[31m Hello World in Red Color\e[0m"
echo -e "\e[32m Hello World in Green Color\e[0m"
echo -e "\e[33m Hello World in Yellow Color\e[0m"
echo -e "\e[34m Hello World in Blue Color\e[0m"
echo -e "\e[35m Hello World in Magenta Color\e[0m"
echo -e "\e[36m Hello World in Cyan Color\e[0m"